const express = require("express");
const router = express.Router();
const getallstudent = require("./getallstudents");
const addstudent = require("./addstudent");
const updatestudent = require("./updatestudent");
const deletestudent = require("./deletestudent");
const loginstudent = require("./loginstudent");
const registerstudent = require("./registerstudent");
const getMarksByStudentId = require("./getMarksByStudentId");
const dashboard = require("./dashboard");
// const getStudentGroupsByCourseId = require("./getStudentGroupsByCourseId");
const getStudentInAGroup = require("./getStudentInAGroup");

router.use(getallstudent);
router.use(addstudent);
router.use(updatestudent);
router.use(deletestudent);
router.use(loginstudent);
router.use(registerstudent);
router.use(getMarksByStudentId);
router.use(dashboard);
//router.use(getStudentGroupsByCourseId);
router.use(getStudentInAGroup);
module.exports = router;